from typing import Protocol, List
import pandas as pd
from matplotlib.figure import Figure

class IVisualizer(Protocol):
    def heatmap(self, df: pd.DataFrame, columns: List[str]) -> Figure: ...
    def boxplot(self, df: pd.DataFrame, column: str, by: str | None = None) -> Figure: ...
    def scatter(self, df: pd.DataFrame, x: str, y: str) -> Figure: ...
    def histogram(self, df: pd.DataFrame, column: str, bins: int = 30) -> Figure: ...
    def dispatch(self, df: pd.DataFrame, step: dict) -> Figure | None: ...